#!/usr/bin/env python3

import argparse
import junit_xml

def write_report(suite_name, test_name, file_name, line_number, failed_message, **other_kwargs):
    a_case = junit_xml.TestCase(name=test_name,
                                file=file_name,
                                line=line_number,
                               )
    a_case.add_failure_info(failed_message)
    ts = junit_xml.TestSuite(suite_name, [a_case])
    print(ts.to_xml_string([ts]))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Write a junit xml report')

    parser.add_argument('-s', '--suite-name',
                        type=str,
                        help="assign name for junit suite of tests",
                        default="ad-hoc tests",
                       )
    parser.add_argument('-n', '--test-name',
                        type=str,
                        required=True,
                        help='name for particular test case',
                       )
    parser.add_argument('-d', '--description',
                        type=str,
                        help="user-readable string describing the case",
                       )
    parser.add_argument('-f', '--file-name',
                        type=str,
                        help="name of the file where the error was found"
                       )
    parser.add_argument('-l', '--line-number',
                        type=int
                       )
    parser.add_argument('-m', '--failed-message',
                        type=str,
                        help='message with details of failure; if None, the test passes',
                       )

    args = parser.parse_args()
    write_report(**vars(args))
